# Generated by Django 3.2.5 on 2021-07-04 10:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.BinaryField(max_length=10000)),
                ("iv", models.BinaryField(max_length=16, null=True)),
                ("locked_till", models.DateTimeField(blank=True, null=True)),
                ("can_be_deleted", models.BooleanField(default=True)),
                ("uuid", models.CharField(max_length=32, null=True)),
                ("creation_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
